env:
  browser: true
  es6: true
  node: true
extends: google
plugins:
- markdown
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2019
rules:
  require-jsdoc: 0
  no-unused-vars: 0
  max-len:
  - 2
  - code: 100
